language: python
dist: xenial
matrix:
  include:
    - python: 3.8
    - python: 3.7
    - python: 3.6
    - python: 3.5

notifications:
  email: false

install: pip install .

script:
  - p2c --help | p2c README.md
  - git diff --exit-code
